package com.c108.springproject.global;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@Getter
public enum ResponseCode {


    SUCCESS_CREATE_QUESTION("SUCCESS_CREATE_QUESTION","문의글 작성 완료"),
    SUCCESS_CREATE_USER("SUCCESS_CREATE_USER","회원가입 완료"),
    SUCCESS_FOUND_USER_LIST("SUCCESS_FOUND_USER_LIST", "회원 리스트 조회 완료"),
    SUCCESS_FIND_ALL_QUESTION("SUCCESS_FIND_ALL_QUESTION", "전체 문의글 조회 완료"),
    SUCCESS_FIND_QUESTION("SUCCESS_FIND_QUESTION", "문의글 조회 완료"),
    QUESTION_NOT_FOUND("QUESTION_NOT_FOUND", "문의글 조회 실패"),
    NOT_FOUND_CATEGORY("NOT_FOUND_CATEGORY", "카테고리 없음"),
    SUCCESS_UPDATE_QUESTION("SUCCESS_UPDATE_QUESTION", "문의글 수정 완료"),
    FAILED_UPDATE_QUESTION("FAILED_UPDATE_QUESTION", "문의글 수정 실패"),
    SUCCESS_DELETE_QUESTION("SUCCESS_DELETE_QUESTION", "문의글 삭제 완료"),

    SUCCESS_CREATE_ITEM("SUCCESS_CREATE_ITEM", "상품 등록 완료"),
    ITEM_NOT_FOUND("ITEM_NOT_FOUND", "아이템 조회 실패"),
    SUCCESS_FIND_ITEM("SUCCESS_FIND_ITEM", "아이템 조회 완료"),
    SUCCESS_UPDATE_ITEM("SUCCESS_UPDATE_ITEM", "아이템 수정 완료"),
    SUCCESS_FIND_CATEGORY("SUCCESS_FIND_CATEGORY", "카테고리 조회 완료"),
    SUCCESS_CREATE_CATEGORY("SUCCESS_CREATE_CATEGORY", "카테고리 생성 완료"),
    SUCCESS_FIND_ALL_CATEGORY("SUCCESS_FIND_ALL_CATEGORY", "전체 카테고리 조회 완료"),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND", "카테고리 조회 실패"),
    FAILED_DELETE_QUESTION("FAILED_DELETE_QUESTION", "문의글 삭제 실패"),

    SUCCESS_FIND_ALL_ITEM("SUCCESS_FIND_ALL_ITEM", "전체 상품 조회 완료"),
    SUCCESS_UPDATE_CATEGORY("SUCCESS_UPDATE_CATEGORY", "카테고리 수정 완료"),

    SUCCESS_FIND_USER("SUCCESS_FIND_USER", "회원 조회 완료"),
    NOT_FOUND_USER("NOT_FOUND_USER", "회원을 찾을 수 없음"),
    SUCCESS_CREATE_RECIPECATEGORY("SUCCESS_CREATE_RECIPECATEGORY", "레시피 카테고리 생성 완료"),
    SUCCESS_FIND_RECIPECATEGORY("SUCCESS_FIND_RECIPECATEGORY", "전체 레시피 카테고리 조회 완료"),
    RECIPECATEGORY_NOT_FOUND("RECIPECATEGORY_NOT_FOUND", "레시피 카테고리 조회 실패"),
    FAILED_UPDATE_CATEGORY("FAILED_UPDATE_CATEGORY", "카테고리 업데이트 실패"),
    SUCCESS_DELETE_CATEGORY("SUCCESS_DELETE_CATEGORY", "카테고리 삭제 성공"),
    FAILED_CREATE_RECIPE("FAILED_CREATE_RECIPE", "레시피 생성 실패"),
    SUCCESS_CREATE_RECIPE("SUCCESS_CREATE_RECIPE", "레시피 생성 성공"),
    SUCCESS_UPDATE_USER("SUCCESS_UPDATE_USER", "회원 수정 완료"),
    FAILED_UPDATE_USER("FAILED_UPDATE_USER", "회원 수정 실패"),
    SUCCESS_CREATE_ANSWER("SUCCESS_CREATE_ANSWER", "문의 답변 작성 성공"),
    FAILED_CREATE_ANSWER("FAILED_CREATE_ANSWER", "문의 답변 작성 실패"),
    SUCCESS_FIND_ANSWER("SUCCESS_FIND_ANSWER", "문의 답변 조회 성공"),
    FAILED_FIND_ANSWER("FAILED_FIND_ANSWER", "문의 답변 조회 실패"),
    RECIPE_NOT_FOUND("RECIPE_NOT_FOUND", "레시피 조회 실패"),
    FAILED_UPDATE_RECIPE("FAILED_UPDATE_RECIPE", "레시피 수정 실패"),
    SUCCESS_UPDATE_RECIPE("SUCCESS_UPDATE_RECIPE", "레시피 수정 성공"),
    SUCCESS_UPDATE_ANSWER("SUCCESS_UPDATE_ANSWER", "문의 답변 수정 성공"),
    FAILED_UPDATE_ANSWER("FAILED_UPDATE_ANSWER", "문의 답변 수정 실패"),
    SUCCESS_DELETE_ANSWER("SUCCESS_DELETE_ANSWER", "문의 답변 삭제 성공"),
    FAILED_DELETE_ANSWER("FAILED_DELETE_ANSWER", "문의 답변 삭제 실패"),
    DELETED_QUESTION("DELETED_QUESTION", "삭제된 문의글"),
    SUCCESS_FIND_ALL_RECIPE("SUCCESS_FIND_ALL_RECIPE", "전체 레시피 조회 완료"),
    SUCCESS_FIND_RECIPE("SUCCESS_FIND_RECIPE", "레시피 조회 완료"),
    SUCCESS_DELETE_RECIPE("SUCCESS_DELETE_RECIPE", "레시피 삭제 성공"),
    SUCCESS_CREATE_NOTICE("SUCCESS_CREATE_NOTICE", "공지사항 작성 성공"),
    FAILED_CREATE_NOTICE("FAILED_CREATE_NOTICE", "공지사항 작성 실패"),
    FAILED_CREATE_QUESTION("FAILED_CREATE_QUESTION", "문의 작성 실패"),
    SUCCESS_FIND_ALL_NOTICE("SUCCESS_FIND_ALL_NOTICE", "전체 공지사항 조회 성공"),
    FAILED_FIND_ALL_NOTICE("FAILED_FIND_ALL_NOTICE", "전체 공지사항 조회 실패"),
    SUCCESS_FIND_NOTICE("SUCCESS_FIND_NOTICE", "공지사항 조회 성공"),
    NOTICE_NOT_FOUND("NOTICE_NOT_FOUND", "공지사항 조회 실패"),
    SUCCESS_UPDATE_NOTICE("SUCCESS_UPDATE_NOTICE", "공지사항 수정 성공"),
    FAILED_UPDATE_NOTICE("FAILED_UPDATE_NOTICE", "공지사항 수정 실패"),
    SUCCESS_DELETE_NOTICE("SUCCESS_DELETE_NOTICE", "공지사항 삭제 성공"),
    FAILED_DELETE_NOTICE("FAILED_DELETE_NOTICE", "공지사항 삭제 실패"),
    ;

    private final String code;
    private final String label;

    ResponseCode(String code, String label) {
        this.code = code;
        this.label = label;
    }

}
