const dummyData = [
  {
    id: 1,
    type: '배송',
    title: '배송이 지연되고 있습니다.',
    content: '주문한 상품이 일주일째 도착하지 않고 있습니다. 확인 부탁드립니다.',
    isAnswered: false,
  },
  {
    id: 2,
    type: '제품',
    title: '상품이 파손되어 도착했습니다.',
    content: '구매한 유기농 과일 세트가 박스에서 터져 있었습니다. 어떻게 처리해야 하나요?',
    isAnswered: true,
  },
  {
    id: 3,
    type: '결제',
    title: '결제 내역이 확인되지 않습니다.',
    content: '카드로 결제를 했는데 결제 내역이 조회되지 않습니다. 확인 부탁드립니다.',
    isAnswered: false,
  },
  {
    id: 4,
    type: '반품',
    title: '상품 반품 요청합니다.',
    content: '유통기한이 지난 상품이 배송되었습니다. 반품을 원합니다.',
    isAnswered: true,
  },
  {
    id: 5,
    type: '기타',
    title: '할인 쿠폰 문의',
    content: '구매 시 사용할 수 있는 할인 쿠폰이 있나요?',
    isAnswered: false,
  },
  {
    id: 6,
    type: '배송',
    title: '배송 상태 확인 요청',
    content: '배송 상태가 "배송 준비 중"에서 멈춰 있습니다. 확인 부탁드립니다.',
    isAnswered: true,
  },
  {
    id: 7,
    type: '제품',
    title: '상품 옵션 변경 문의',
    content: '주문한 상품의 색상을 변경하고 싶습니다. 가능할까요?',
    isAnswered: false,
  },
  {
    id: 8,
    type: '결제',
    title: '결제 취소 요청',
    content: '잘못 결제된 내역이 있습니다. 취소 부탁드립니다.',
    isAnswered: true,
  },
  {
    id: 9,
    type: '반품',
    title: '반품 절차 문의',
    content: '반품 절차에 대해 상세히 알려주세요.',
    isAnswered: false,
  },
  {
    id: 10,
    type: '기타',
    title: '상품 추천 요청',
    content: '선물용으로 좋은 상품을 추천해 주세요.',
    isAnswered: false,
  },
  {
    id: 11,
    type: '배송',
    title: '배송 기사 연락처 문의',
    content: '배송 기사의 연락처를 알고 싶습니다.',
    isAnswered: true,
  },
  {
    id: 12,
    type: '제품',
    title: '상품 설명이 잘못되었습니다.',
    content: '구매한 상품의 설명과 실제 제품이 다릅니다.',
    isAnswered: false,
  },
  {
    id: 13,
    type: '결제',
    title: '영수증 재발행 요청',
    content: '구매한 내역의 영수증을 다시 받고 싶습니다.',
    isAnswered: true,
  },
  {
    id: 14,
    type: '반품',
    title: '반품 접수 완료 여부 확인',
    content: '반품 접수가 제대로 되었는지 확인 부탁드립니다.',
    isAnswered: true,
  },
  {
    id: 15,
    type: '기타',
    title: '회원 탈퇴 방법 문의',
    content: '회원 탈퇴를 하려면 어떻게 해야 하나요?',
    isAnswered: false,
  },
  {
    id: 16,
    type: '배송',
    title: '배송 주소 변경 요청',
    content: '잘못된 주소로 입력된 것을 수정하고 싶습니다.',
    isAnswered: false,
  },
  {
    id: 17,
    type: '제품',
    title: '부품 누락 문제',
    content: '구매한 제품에 부품이 하나 빠져 있습니다.',
    isAnswered: true,
  },
  {
    id: 18,
    type: '결제',
    title: '할부 결제 문의',
    content: '할부 결제가 가능한지 알고 싶습니다.',
    isAnswered: false,
  },
  {
    id: 19,
    type: '반품',
    title: '반품 진행 상태 문의',
    content: '반품 진행 상태를 확인하고 싶습니다.',
    isAnswered: true,
  },
  {
    id: 20,
    type: '기타',
    title: '정기배송 설정 방법',
    content: '정기배송은 어떻게 설정할 수 있나요?',
    isAnswered: false,
  },
]

export default dummyData
